---
trigger:
  - main
pool:
 vmImage: "ubuntu-22.04"

stages:
  - stage: "BuildStage"
    displayName: "Building .Net code"
    jobs:
      - job: "Building"
        displayName: "Building .Net code"
        steps:
          - task: DotNetCoreCLI@2
            inputs:
              command: 'build'
          - task: DotNetCoreCLI@2
            inputs:
              command: test
  - stage: "Publish"
    jobs:
      - job: "DotNetPublish" 
        steps:
          - task: DotNetCoreCLI@2
            inputs:
              command: publish
              arguments: '-o $(Build.ArtifactStagingDirectory)/Output'
              zipAfterPublish: true
              modifyOutputPath: true
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/Output'
              ArtifactName: DbConTest

  - stage: "Deploy"
    dependsOn: "Publish"
    jobs:
      - deployment: "DeployWebApp"
        displayName: "Deploy Web App"
        environment: 'Dev'
        strategy:
         runOnce:
          deploy:
            steps:
              - task: AzureWebApp@1
                inputs:
                  azureSubscription: 'AppServiceCon'
                  appName: 'DbContester'
                  package: '$(Pipeline.Workspace)/DbConTest/*.zip'
                  appType: webApp
           

             
              



            
              