apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbtester   # must be lowercase
spec:
  minReadySeconds: 10
  replicas: 2
  selector:
    matchLabels:
      app: dbcontester   # lowercase
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dbcontester   # lowercase
    spec:
      containers:
        - name: dbcontester   # lowercase
          image: bluedock.azurecr.io/repo1:latest   # pipeline will override with BuildId
          ports:
            - containerPort: 8080
              protocol: TCP
