apiVersion: v1
kind: Service
metadata:
  name: dbcontester-service   # lowercase
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: dbcontester   # must match label in deployment
  type: LoadBalancer
